# frozen_string_literal: true

# Crontab entries generated by the `whenever` gem (bundle exec whenever).
# Update cron with:  bundle exec whenever --update-crontab piaf_api
# Remove with:       bundle exec whenever --clear-crontab piaf_api

job_type :rake, "cd :path && :environment_variable=:environment bundle exec rake :task --silent :output"

every 1.day, at: "2:00 am" do
  rake "scheduled:expire_pending_enrollments"
end

every 1.day, at: "3:00 am" do
  rake "scheduled:deactivate_inactive_students"
end

every 1.day, at: "4:00 am" do
  rake "scheduled:maintenance"
end
